<a href="https://colab.research.google.com/github/DiAnCaceres/Minor-Machine-Learning/blob/main/Proyecto_ML/Proyecto_ML_Semana1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Obtain

In [1]:
import pandas as pd # amnipulacion de datos
import numpy as np # parte numerica
import matplotlib.pyplot as plt # visualizacion grafica
import seaborn as sns # mejora graficas, paletas de colores

In [20]:
url = "https://drive.google.com/file/d/1Nacn6CvB6xcltzx-_hp5AHw2YkME1iiB/view?usp=share_link" #link del dataset(link hacia .txt que esta in mi gdrive)
url = "https://drive.google.com/uc?id=" + url.split('/')[-2]
dataset = pd.read_csv(url, header = None, on_bad_lines='skip') #se agrego on_bad_lines skip ya que daba error al cargar el dataset
dataset

          0        1                2         3          4             5
0        33  Jogging   49105962326000 -0.694638  12.680544   0.50395286;
1        33  Jogging   49106062271000  5.012288  11.264028   0.95342433;
2        33  Jogging   49106112167000  4.903325  10.882658  -0.08172209;
3        33  Jogging   49106222305000 -0.612916  18.496431    3.0237172;
4        33  Jogging   49106332290000 -1.184970  12.108489     7.205164;
...      ..      ...              ...       ...        ...           ...
1086461  19  Sitting  131623331483000  9.000000  -1.570000         1.69;
1086462  19  Sitting  131623371431000  9.040000  -1.460000         1.73;
1086463  19  Sitting  131623411592000  9.080000  -1.380000         1.69;
1086464  19  Sitting  131623491487000  9.000000  -1.460000         1.73;
1086465  19  Sitting  131623531465000  8.880000  -1.330000         1.61;

[1086466 rows x 6 columns]